#include "iteminfo.h"

static ItemInfo items[256] =
{
	[1] = {.name="Master Ball", .filename="master-ball.png"},
	[2] = {.name="Ultra Ball", .filename="ultra-ball.png"},
	[3] = {.name="Great Ball", .filename="great-ball.png"},
	[4] = {.name="Poke Ball", .filename="poke-ball.png"},
	[5] = {.name="Town Map", .filename="town-map.png"},
	[6] = {.name="Bicycle", .filename="bicycle.png"},
	[8] = {.name="Safari Ball", .filename="safari-ball.png"},
	[10] = {.name="Moon Stone", .filename="moon-stone.png"},
	[11] = {.name="Antidote", .filename="antidote.png"},
	[12] = {.name="Burn Heal", .filename="burn-heal.png"},
	[13] = {.name="Ice Heal", .filename="ice-heal.png"},
	[14] = {.name="Awakening", .filename="awakening.png"},
	[15] = {.name="Parlyz Heal", .filename="parlyz-heal.png"},
	[16] = {.name="Full Restore", .filename="full-restore.png"},
	[17] = {.name="Max Potion", .filename="max-potion.png"},
	[18] = {.name="Hyper Potion", .filename="hyper-potion.png"},
	[19] = {.name="Super Potion", .filename="super-potion.png"},
	[20] = {.name="Potion", .filename="potion.png"},
	[29] = {.name="Escape Rope", .filename="escape-rope.png"},
	[30] = {.name="Repel", .filename="repel.png"},
	[31] = {.name="Old Amber", .filename="old-amber.png"},
	[32] = {.name="Fire Stone", .filename="fire-stone.png"},
	[33] = {.name="Thunder stone", .filename="thunder-stone.png"},
	[34] = {.name="Water Stone", .filename="water-stone.png"},
	[35] = {.name="HP Up", .filename="hp-up.png"},
	[36] = {.name="Protein", .filename="protein.png"},
	[37] = {.name="Iron", .filename="iron.png"},
	[38] = {.name="Carbos", .filename="carbos.png"},
	[39] = {.name="Calcium", .filename="calcium.png"},
	[40] = {.name="Rare Candy", .filename="rare-candy.png"},
	[41] = {.name="Dome Fossil", .filename="dome-fossil.png"},
	[42] = {.name="Helix Fossil", .filename="helix-fossil.png"},
	[43] = {.name="Secret Key", .filename="secret-key.png"},
	[45] = {.name="Bike Voucher", .filename="bike-voucher.png"},
	[46] = {.name="X Accuracy", .filename="x-accuracy.png"},
	[47] = {.name="Leaf Stone", .filename="leaf-stone.png"},
	[48] = {.name="Card Key", .filename="card-key.png"},
	[49] = {.name="Nugget", .filename="nugget.png"},
	[51] = {.name="Poke Doll", .filename="poke-doll.png"},
	[52] = {.name="Full Heal", .filename="full-heal.png"},
	[53] = {.name="Revive", .filename="revive.png"},
	[54] = {.name="Max Revive", .filename="max-revive.png"},
	[55] = {.name="Guard Spec.", .filename="guard-spec.png"},
	[56] = {.name="Super Repel", .filename="super-repel.png"},
	[57] = {.name="Max Repel", .filename="max-repel.png"},
	[58] = {.name="Dire Hit", .filename="dire-hit.png"},
	[60] = {.name="Fresh Water", .filename="fresh-water.png"},
	[61] = {.name="Soda Pop", .filename="soda-pop.png"},
	[62] = {.name="Lemonade", .filename="lemonade.png"},
	[63] = {.name="S.S. Ticket", .filename="ss-ticket.png"},
	[64] = {.name="Gold Teeth", .filename="gold-teeth.png"},
	[65] = {.name="X Attack", .filename="x-attack.png"},
	[66] = {.name="X Defend", .filename="x-defend.png"},
	[67] = {.name="X Speed", .filename="x-speed.png"},
	[68] = {.name="X Special", .filename="x-special.png"},
	[69] = {.name="Coin Case", .filename="coin-case.png"},
	[70] = {.name="Oak's Parcel", .filename="oaks-parcel.png"},
	[71] = {.name="Item Finder", .filename="itemfinder.png"},
	[72] = {.name="Silph Scope", .filename="silph-scope.png"},
	[73] = {.name="Poke Flute", .filename="poke-flute.png"},
	[74] = {.name="Lift Key", .filename="lift-key.png"},
	[75] = {.name="Exp. All", .filename="exp-all.png"},
	[76] = {.name="Old Rod", .filename="old-rod.png"},
	[77] = {.name="Good Rod", .filename="good-rod.png"},
	[78] = {.name="Super Rod", .filename="super-rod.png"},
	[79] = {.name="PP Up", .filename="pp-up.png"},
	[80] = {.name="Ether", .filename="ether.png"},
	[81] = {.name="Max Ether", .filename="max-ether.png"},
	[82] = {.name="Elixer", .filename="elixer.png"},
	[83] = {.name="Max Elixer", .filename="max-elixer.png"},
	[196] = {.name="HM01", .filename="normal.png"},
	[197] = {.name="HM02", .filename="flying.png"},
	[198] = {.name="HM03", .filename="water.png"},
	[199] = {.name="HM04", .filename="normal.png"},
	[200] = {.name="HM05", .filename="normal.png"},
	[201] = {.name="TM01", .filename="normal.png"},
	[202] = {.name="TM02", .filename="normal.png"},
	[203] = {.name="TM03", .filename="normal.png"},
	[204] = {.name="TM04", .filename="normal.png"},
	[205] = {.name="TM05", .filename="normal.png"},
	[206] = {.name="TM06", .filename="poison.png"},
	[207] = {.name="TM07", .filename="normal.png"},
	[208] = {.name="TM08", .filename="normal.png"},
	[209] = {.name="TM09", .filename="normal.png"},
	[210] = {.name="TM10", .filename="normal.png"},
	[211] = {.name="TM11", .filename="water.png"},
	[212] = {.name="TM12", .filename="water.png"},
	[213] = {.name="TM13", .filename="ice.png"},
	[214] = {.name="TM14", .filename="ice.png"},
	[215] = {.name="TM15", .filename="normal.png"},
	[216] = {.name="TM16", .filename="normal.png"},
	[217] = {.name="TM17", .filename="fighting.png"},
	[218] = {.name="TM18", .filename="fighting.png"},
	[219] = {.name="TM19", .filename="fighting.png"},
	[220] = {.name="TM20", .filename="normal.png"},
	[221] = {.name="TM21", .filename="grass.png"},
	[222] = {.name="TM22", .filename="grass.png"},
	[223] = {.name="TM23", .filename="dragon.png"},
	[224] = {.name="TM24", .filename="electric.png"},
	[225] = {.name="TM25", .filename="electric.png"},
	[226] = {.name="TM26", .filename="ground.png"},
	[227] = {.name="TM27", .filename="ground.png"},
	[228] = {.name="TM28", .filename="ground.png"},
	[229] = {.name="TM29", .filename="psychic.png"},
	[230] = {.name="TM30", .filename="psychic.png"},
	[231] = {.name="TM31", .filename="normal.png"},
	[232] = {.name="TM32", .filename="normal.png"},
	[233] = {.name="TM33", .filename="psychic.png"},
	[234] = {.name="TM34", .filename="normal.png"},
	[235] = {.name="TM35", .filename="normal.png"},
	[236] = {.name="TM36", .filename="normal.png"},
	[237] = {.name="TM37", .filename="normal.png"},
	[238] = {.name="TM38", .filename="fire.png"},
	[239] = {.name="TM39", .filename="normal.png"},
	[240] = {.name="TM40", .filename="normal.png"},
	[241] = {.name="TM41", .filename="normal.png"},
	[242] = {.name="TM42", .filename="psychic.png"},
	[243] = {.name="TM43", .filename="flying.png"},
	[244] = {.name="TM44", .filename="psychic.png"},
	[245] = {.name="TM45", .filename="electric.png"},
	[246] = {.name="TM46", .filename="psychic.png"},
	[247] = {.name="TM47", .filename="normal.png"},
	[248] = {.name="TM48", .filename="rock.png"},
	[249] = {.name="TM49", .filename="normal.png"},
	[250] = {.name="TM50", .filename="normal.png"},
};

ItemInfo get_item_info(int id)
{
	return items[id];
}
