#include "pokeinfo.h"

static Info items[256] =
{
	[1] = {.name="Master Ball", .filename="master-ball.png"},
	[2] = {.name="Ultra Ball", .filename="ultra-ball.png"},
	[3] = {.name="Great Ball", .filename="great-ball.png"},
	[4] = {.name="Poke Ball", .filename="poke-ball.png"},
	[5] = {.name="Town Map", .filename="town-map.png"},
	[6] = {.name="Bicycle", .filename="bicycle.png"},
	[8] = {.name="Safari Ball", .filename="safari-ball.png"},
	[10] = {.name="Moon Stone", .filename="moon-stone.png"},
	[11] = {.name="Antidote", .filename="antidote.png"},
	[12] = {.name="Burn Heal", .filename="burn-heal.png"},
	[13] = {.name="Ice Heal", .filename="ice-heal.png"},
	[14] = {.name="Awakening", .filename="awakening.png"},
	[15] = {.name="Parlyz Heal", .filename="parlyz-heal.png"},
	[16] = {.name="Full Restore", .filename="full-restore.png"},
	[17] = {.name="Max Potion", .filename="max-potion.png"},
	[18] = {.name="Hyper Potion", .filename="hyper-potion.png"},
	[19] = {.name="Super Potion", .filename="super-potion.png"},
	[20] = {.name="Potion", .filename="potion.png"},
	[29] = {.name="Escape Rope", .filename="escape-rope.png"},
	[30] = {.name="Repel", .filename="repel.png"},
	[31] = {.name="Old Amber", .filename="old-amber.png"},
	[32] = {.name="Fire Stone", .filename="fire-stone.png"},
	[33] = {.name="Thunder stone", .filename="thunder-stone.png"},
	[34] = {.name="Water Stone", .filename="water-stone.png"},
	[35] = {.name="HP Up", .filename="hp-up.png"},
	[36] = {.name="Protein", .filename="protein.png"},
	[37] = {.name="Iron", .filename="iron.png"},
	[38] = {.name="Carbos", .filename="carbos.png"},
	[39] = {.name="Calcium", .filename="calcium.png"},
	[40] = {.name="Rare Candy", .filename="rare-candy.png"},
	[41] = {.name="Dome Fossil", .filename="dome-fossil.png"},
	[42] = {.name="Helix Fossil", .filename="helix-fossil.png"},
	[43] = {.name="Secret Key", .filename="secret-key.png"},
	[45] = {.name="Bike Voucher", .filename="bike-voucher.png"},
	[46] = {.name="X Accuracy", .filename="x-accuracy.png"},
	[47] = {.name="Leaf Stone", .filename="leaf-stone.png"},
	[48] = {.name="Card Key", .filename="card-key.png"},
	[49] = {.name="Nugget", .filename="nugget.png"},
	[51] = {.name="Poke Doll", .filename="poke-doll.png"},
	[52] = {.name="Full Heal", .filename="full-heal.png"},
	[53] = {.name="Revive", .filename="revive.png"},
	[54] = {.name="Max Revive", .filename="max-revive.png"},
	[55] = {.name="Guard Spec.", .filename="guard-spec.png"},
	[56] = {.name="Super Repel", .filename="super-repel.png"},
	[57] = {.name="Max Repel", .filename="max-repel.png"},
	[58] = {.name="Dire Hit", .filename="dire-hit.png"},
	[60] = {.name="Fresh Water", .filename="fresh-water.png"},
	[61] = {.name="Soda Pop", .filename="soda-pop.png"},
	[62] = {.name="Lemonade", .filename="lemonade.png"},
	[63] = {.name="S.S. Ticket", .filename="ss-ticket.png"},
	[64] = {.name="Gold Teeth", .filename="gold-teeth.png"},
	[65] = {.name="X Attack", .filename="x-attack.png"},
	[66] = {.name="X Defend", .filename="x-defend.png"},
	[67] = {.name="X Speed", .filename="x-speed.png"},
	[68] = {.name="X Special", .filename="x-special.png"},
	[69] = {.name="Coin Case", .filename="coin-case.png"},
	[70] = {.name="Oak's Parcel", .filename="oaks-parcel.png"},
	[71] = {.name="Item Finder", .filename="itemfinder.png"},
	[72] = {.name="Silph Scope", .filename="silph-scope.png"},
	[73] = {.name="Poke Flute", .filename="poke-flute.png"},
	[74] = {.name="Lift Key", .filename="lift-key.png"},
	[75] = {.name="Exp. All", .filename="exp-all.png"},
	[76] = {.name="Old Rod", .filename="old-rod.png"},
	[77] = {.name="Good Rod", .filename="good-rod.png"},
	[78] = {.name="Super Rod", .filename="super-rod.png"},
	[79] = {.name="PP Up", .filename="pp-up.png"},
	[80] = {.name="Ether", .filename="ether.png"},
	[81] = {.name="Max Ether", .filename="max-ether.png"},
	[82] = {.name="Elixer", .filename="elixer.png"},
	[83] = {.name="Max Elixer", .filename="max-elixer.png"},
	[196] = {.name="HM01", .filename="normal.png"},
	[197] = {.name="HM02", .filename="flying.png"},
	[198] = {.name="HM03", .filename="water.png"},
	[199] = {.name="HM04", .filename="normal.png"},
	[200] = {.name="HM05", .filename="normal.png"},
	[201] = {.name="TM01", .filename="normal.png"},
	[202] = {.name="TM02", .filename="normal.png"},
	[203] = {.name="TM03", .filename="normal.png"},
	[204] = {.name="TM04", .filename="normal.png"},
	[205] = {.name="TM05", .filename="normal.png"},
	[206] = {.name="TM06", .filename="poison.png"},
	[207] = {.name="TM07", .filename="normal.png"},
	[208] = {.name="TM08", .filename="normal.png"},
	[209] = {.name="TM09", .filename="normal.png"},
	[210] = {.name="TM10", .filename="normal.png"},
	[211] = {.name="TM11", .filename="water.png"},
	[212] = {.name="TM12", .filename="water.png"},
	[213] = {.name="TM13", .filename="ice.png"},
	[214] = {.name="TM14", .filename="ice.png"},
	[215] = {.name="TM15", .filename="normal.png"},
	[216] = {.name="TM16", .filename="normal.png"},
	[217] = {.name="TM17", .filename="fighting.png"},
	[218] = {.name="TM18", .filename="fighting.png"},
	[219] = {.name="TM19", .filename="fighting.png"},
	[220] = {.name="TM20", .filename="normal.png"},
	[221] = {.name="TM21", .filename="grass.png"},
	[222] = {.name="TM22", .filename="grass.png"},
	[223] = {.name="TM23", .filename="dragon.png"},
	[224] = {.name="TM24", .filename="electric.png"},
	[225] = {.name="TM25", .filename="electric.png"},
	[226] = {.name="TM26", .filename="ground.png"},
	[227] = {.name="TM27", .filename="ground.png"},
	[228] = {.name="TM28", .filename="ground.png"},
	[229] = {.name="TM29", .filename="psychic.png"},
	[230] = {.name="TM30", .filename="psychic.png"},
	[231] = {.name="TM31", .filename="normal.png"},
	[232] = {.name="TM32", .filename="normal.png"},
	[233] = {.name="TM33", .filename="psychic.png"},
	[234] = {.name="TM34", .filename="normal.png"},
	[235] = {.name="TM35", .filename="normal.png"},
	[236] = {.name="TM36", .filename="normal.png"},
	[237] = {.name="TM37", .filename="normal.png"},
	[238] = {.name="TM38", .filename="fire.png"},
	[239] = {.name="TM39", .filename="normal.png"},
	[240] = {.name="TM40", .filename="normal.png"},
	[241] = {.name="TM41", .filename="normal.png"},
	[242] = {.name="TM42", .filename="psychic.png"},
	[243] = {.name="TM43", .filename="flying.png"},
	[244] = {.name="TM44", .filename="psychic.png"},
	[245] = {.name="TM45", .filename="electric.png"},
	[246] = {.name="TM46", .filename="psychic.png"},
	[247] = {.name="TM47", .filename="normal.png"},
	[248] = {.name="TM48", .filename="rock.png"},
	[249] = {.name="TM49", .filename="normal.png"},
	[250] = {.name="TM50", .filename="normal.png"},
};

Info pokemon[191] = 
{
	[1] = {.name="Rhydon", .filename="rhydon.png"},
	[2] = {.name="Kangaskhan", .filename="kangaskhan.png"},
	[3] = {.name="Nidoran M", .filename="nidoran-m.png"},	
	[4] = {.name="Clefairy", .filename="clefairy.png"},
	[5] = {.name="Spearow", .filename="spearow.png"},
	[6] = {.name="Voltorb", .filename="voltorb.png"},
	[7] = {.name="Nidoking", .filename="nidoking.png"},
	[8] = {.name="Slowbro", .filename="slowbro.png"},
	[9] = {.name="Ivysaur", .filename="ivysaur.png"},
	[10] = {.name="Exeggutor", .filename="exeggutor.png"},
	[11] = {.name="Lickitung", .filename="lickitung.png"},
	[12] = {.name="Exeggcute", .filename="exeggcute.png"},
	[13] = {.name="Grimer", .filename="grimer.png"},
	[14] = {.name="Gengar", .filename="gengar.png"},
	[15] = {.name="Nidoran F", .filename="nidoran-f.png"},
	[16] = {.name="Nidoqueen", .filename="nidoqueen.png"},
	[17] = {.name="Cubone", .filename="cubone.png"},
	[18] = {.name="Rhyhorn", .filename="rhyhorn.png"},
	[19] = {.name="Lapras", .filename="lapras.png"},
	[20] = {.name="Arcanine", .filename="arcanine.png"},
	[21] = {.name="Mew", .filename="mew.png"},
	[22] = {.name="Gyarados", .filename="gyarados.png"},
	[23] = {.name="Shellder", .filename="shellder.png"},
	[24] = {.name="Tentacool", .filename="tentacool.png"},
	[25] = {.name="Gastly", .filename="gastly.png"},
	[26] = {.name="Scyther", .filename="scyther.png"},
	[27] = {.name="Staryu", .filename="staryu.png"},
	[28] = {.name="Blastoise", .filename="blastoise.png"},
	[29] = {.name="Pinsir", .filename="pinsir.png"},
	[30] = {.name="Tangela", .filename="tangela.png"},
	[33] = {.name="Growlithe", .filename="growlithe.png"},
	[34] = {.name="Onix", .filename="onix.png"},
	[35] = {.name="Fearow", .filename="fearow.png"},
	[36] = {.name="Pidgey", .filename="pidgey.png"},
	[37] = {.name="Slowpoke", .filename="slowpoke.png"},
	[38] = {.name="Kadabra", .filename="kadabra.png"},
	[39] = {.name="Graveler", .filename="graveler.png"},
	[40] = {.name="Chansey", .filename="chansey.png"},
	[41] = {.name="Machoke", .filename="machoke.png"},
	[42] = {.name="Mr. Mime", .filename="mr-mime.png"},
	[43] = {.name="Mitmonlee", .filename="hitmonlee.png"},
	[44] = {.name="Hitmonchan", .filename="hitmonchand.png"},
	[45] = {.name="Arbok", .filename="arbok.png"},
	[46] = {.name="Parasect", .filename="parasect.png"},
	[47] = {.name="Psyduck", .filename="psyduck.png"},
	[48] = {.name="Drowzee", .filename="drowzee.png"},
	[49] = {.name="Golem", .filename="golem.png"},
	[51] = {.name="Magmar", .filename="magmar.png"},
	[53] = {.name="Electabuzz", .filename="electabuzz.png"},
	[54] = {.name="Magneton", .filename="magneton.png"},
	[55] = {.name="Koffing", .filename="koffing.png"},
	[57] = {.name="Mankey", .filename="mankey.png"},
	[58] = {.name="Seel", .filename="seel.png"},
	[59] = {.name="Diglett", .filename="diglett.png"},
	[60] = {.name="Tauros", .filename="tauros.png"},
	[64] = {.name="Farfetch'd", .filename="farfetchd.png"},
	[65] = {.name="Venonat", .filename="venonat.png"},
	[66] = {.name="Dragonite", .filename="dragonite.png"},
	[70] = {.name="Doduo", .filename="doduo.png"},
	[71] = {.name="Poliwag", .filename="poliwag.png"},
	[72] = {.name="Jynx", .filename="jynx.png"},
	[73] = {.name="Moltres", .filename="moltres.png"},
	[74] = {.name="Articuno", .filename="articuno.png"},
	[75] = {.name="Zapdos", .filename="zapdos.png"},
	[76] = {.name="Ditto", .filename="ditto.png"},
	[77] = {.name="Meowth", .filename="meowth.png"},
	[78] = {.name="Krabby", .filename="krabby.png"},
	[82] = {.name="Vulpix", .filename="vulpix.png"},
	[83] = {.name="Ninetales", .filename="ninetales.png"},
	[84] = {.name="Pikachu", .filename="pikachu.png"},
	[85] = {.name="Raichu", .filename="raichu.png"},
	[88] = {.name="Dratini", .filename="dratini.png"},
	[89] = {.name="Dragonair", .filename="dragonair.png"},
	[90] = {.name="Kabuto", .filename="kabuto.png"},
	[91] = {.name="Kabutops", .filename="kabutops.png"},
	[92] = {.name="Horsea", .filename="horsea.png"},
	[93] = {.name="Seadra", .filename="seadra.png"},
	[96] = {.name="Sandshrew", .filename="sandshrew.png"},
	[97] = {.name="Sandslash", .filename="sandslash.png"},
	[98] = {.name="Omanyte", .filename="omanyte.png"},
	[99] = {.name="Omastar", .filename="omastar.png"},
	[100] = {.name="Jigglypuff", .filename="jugglypuff.png"},
	[101] = {.name="Wigglytuff", .filename="wigglytuff.png"},
	[102] = {.name="Eevee", .filename="eevee.png"},
	[103] = {.name="Flareon", .filename="flareon.png"},
	[104] = {.name="Jolteon", .filename="jolteon.png"},
	[105] = {.name="Vaporeon", .filename="vaporeon.png"},
	[106] = {.name="Machop", .filename="machop.png"},
	[107] = {.name="Zubat", .filename="zubat.png"},
	[108] = {.name="Ekans", .filename="ekans.png"},
	[109] = {.name="Paras", .filename="paras.png"},
	[110] = {.name="Poliwhirl", .filename="poliwhirl.png"},
	[111] = {.name="Poliwrath", .filename="poliwrath.png"},
	[112] = {.name="Weedle", .filename="weedle.png"},
	[113] = {.name="Kakuna", .filename="kakuna.png"},
	[114] = {.name="Beedrill", .filename="beedrill.png"},
	[116] = {.name="Dodrio", .filename="dodrio.png"},
	[117] = {.name="Primeape", .filename="primeape.png"},
	[118] = {.name="Dugtrio", .filename="dugtrio.png"},
	[119] = {.name="Venomoth", .filename="venomoth.png"},
	[120] = {.name="Dewgong", .filename="dewgong.png"},
	[123] = {.name="Caterpie", .filename="caterpie.png"},
	[124] = {.name="Metapod", .filename="Metapod.png"},
	[125] = {.name="Butterfree", .filename="butterfree.png"},
	[126] = {.name="Machamp", .filename="machamp.png"},
	[128] = {.name="Golduck", .filename="golduck.png"},
	[129] = {.name="Hypno", .filename="hypno.png"},
	[130] = {.name="Golbat", .filename="golbat.png"},
	[131] = {.name="Mewtwo", .filename="mewtwo.png"},
	[132] = {.name="Snorlax", .filename="snorlax.png"},
	[133] = {.name="Magikarp", .filename="magikarp.png"},
	[136] = {.name="Muk", .filename="muk.png"},
	[138] = {.name="Kingler", .filename="kingler.png"},
	[139] = {.name="Cloyster", .filename="cloyster.png"},
	[141] = {.name="Electrode", .filename="electrode.png"},
	[142] = {.name="Clefable", .filename="clefable.png"},
	[143] = {.name="Weezing", .filename="weezing.png"},
	[144] = {.name="Persian", .filename="persian.png"},
	[145] = {.name="Marowak", .filename="marowak.png"},
	[147] = {.name="Haunter", .filename="haunter.png"},
	[148] = {.name="Abra", .filename="abra.png"},
	[149] = {.name="Alakazam", .filename="alakazam.png"},
	[150] = {.name="Pidgeotto", .filename="pidgeotto.png"},
	[151] = {.name="Pidgeot", .filename="pidgeot.png"},
	[152] = {.name="Starmie", .filename="starmie.png"},
	[153] = {.name="Bulbasaur", .filename="bulbasaur.png"},
	[154] = {.name="Venusaur", .filename="venusaur.png"},
	[155] = {.name="Tentacruel", .filename="tentacruel.png"},
	[157] = {.name="Goldeen", .filename="goldeen.png"},
	[158] = {.name="Seaking", .filename="seaking.png"},
	[163] = {.name="Ponyta", .filename="ponyta.png"},
	[164] = {.name="Rapidash", .filename="rapidash.png"},
	[165] = {.name="Rattata", .filename="rattata.png"},
	[166] = {.name="Raticate", .filename="raticate.png"},
	[167] = {.name="Nidorino", .filename="nidorino.png"},
	[168] = {.name="Nidorina", .filename="nidorina.png"},
	[169] = {.name="Geodude", .filename="geodude.png"},
	[170] = {.name="Porygon", .filename="porygon.png"},
	[171] = {.name="Aerodactyl", .filename="aerodactyl.png"},
	[173] = {.name="Magnemite", .filename="magnemite.png"},
	[176] = {.name="Charmander", .filename="charmander.png"},
	[177] = {.name="Squirtle", .filename="squirtle.png"},
	[178] = {.name="Charmeleon", .filename="charmeleon.png"},
	[179] = {.name="Wartortle", .filename="wartortle.png"},
	[180] = {.name="Charizard", .filename="charizard.png"},
	[185] = {.name="Oddish", .filename="oddish.png"},
	[186] = {.name="Gloom", .filename="gloom.png"},
	[187] = {.name="Vileplume", .filename="vileplume.png"},
	[188] = {.name="Bellsprout", .filename="bellsprout.png"},
	[189] = {.name="Weepinbell", .filename="weepinbell.png"},
	[190] = {.name="Victreebel", .filename="victreebel.png"},
};

static PokemonBaseStats pokemon_stats[] =
{
	[1] = {.hp=105, .attack=130, .defense=120, .speed=40, .special=45},
	[2] = {.hp=105, .attack=95, .defense=80, .speed=90, .special=40},
	[3] = {.hp=46, .attack=57, .defense=40, .speed=50, .special=40},
	[4] = {.hp=70, .attack=45, .defense=48, .speed=35, .special=60},
	[5] = {.hp=40, .attack=60, .defense=30, .speed=70, .special=31},
	[6] = {.hp=40, .attack=30, .defense=50, .speed=100, .special=55},
	[7] = {.hp=81, .attack=92, .defense=77, .speed=85, .special=75},
	[8] = {.hp=95, .attack=75, .defense=110, .speed=30, .special=80},
	[9] = {.hp=60, .attack=62, .defense=63, .speed=60, .special=80},
	[10] = {.hp=95, .attack=95, .defense=85, .speed=55, .special=125},
	[11] = {.hp=90, .attack=55, .defense=75, .speed=30, .special=60},
	[12] = {.hp=60, .attack=40, .defense=80, .speed=40, .special=60},
	[13] = {.hp=80, .attack=80, .defense=50, .speed=25, .special=40},
	[14] = {.hp=60, .attack=65, .defense=60, .speed=110, .special=130},
	[15] = {.hp=55, .attack=47, .defense=52, .speed=41, .special=40},
	[16] = {.hp=90, .attack=82, .defense=87, .speed=76, .special=75},
	[17] = {.hp=50, .attack=50, .defense=95, .speed=35, .special=40},
	[18] = {.hp=80, .attack=85, .defense=95, .speed=25, .special=30},
	[19] = {.hp=130, .attack=85, .defense=80, .speed=60, .special=95},
	[20] = {.hp=90, .attack=110, .defense=80, .speed=95, .special=80},
	[21] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[22] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[23] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[24] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[25] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[26] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[27] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[28] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[29] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[30] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[33] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[34] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[35] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[36] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[37] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[38] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[39] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[40] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[41] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[42] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[43] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[44] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[45] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[46] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[47] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[48] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[49] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[51] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[53] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[54] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[55] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[57] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[58] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[59] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[60] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[64] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[65] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[66] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[70] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[71] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[72] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[73] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[74] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[75] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[76] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[77] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[78] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[82] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[83] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[84] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[85] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[88] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[89] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[90] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[91] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[92] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[93] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[96] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[97] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[98] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[99] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[100] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[101] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[102] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[103] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[104] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[105] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[106] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[107] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[108] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[109] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[110] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[111] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[112] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[113] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[114] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[116] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[117] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[118] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[119] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[120] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[123] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[124] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[125] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[126] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[128] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[129] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[130] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[131] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[132] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[133] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[136] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[138] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[139] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[141] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[142] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[143] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[144] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[145] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[147] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[148] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[149] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[150] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[151] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[152] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[153] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[154] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[155] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[157] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[158] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[163] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[164] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[165] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[166] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[167] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[168] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[169] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[170] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[171] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[173] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[176] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[177] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[178] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[179] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[180] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[185] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[186] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[187] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[188] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[189] = {.hp=, .attack=, .defense=, .speed=, .special=},
	[190] = {.hp=, .attack=, .defense=, .speed=, .special=},
}

Info get_item_info(int id)
{
	return items[id];
}

Info get_pokemon_info(int id)
{
	return pokemon[id];
}

PokemonBaseStats get_pokemon_base_stats(int id)
{
	return pokemon_stats[id];
}
